packages:
  - frontend
  - backend
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@snaplet/seed': true
  esbuild: true
  supabase: true

ignoredBuiltDependencies:
  - supabase

onlyBuiltDependencies:
  - '@prisma/engines'
  - '@snaplet/seed'
  - esbuild
