packages:
  - frontend
  - backend/**
  - packages/**
  - "!**/node_modules/**" # Do not scan nested node_modules

allowBuilds:
  "@prisma/engines": true
  "@snaplet/seed": true
  esbuild: true
  sharp: true
  supabase: true

ignoredBuiltDependencies:
  - supabase

onlyBuiltDependencies:
  - "@prisma/engines"
  - "@snaplet/seed"
  - esbuild
