import { SupabaseDB } from "@shared/types.d.ts";
import { User } from "supabase";

async function createNewUser(
  role: "user" | "admin",
  supabaseService: SupabaseDB,
) {
  const { data, error } = await supabaseService.auth.admin.createUser({
    email: "user@example.com",
    password: "securePassword123",
    email_confirm: true, // Skip email confirmation
    app_metadata: { role },
  });

  if (error) {
    console.error("Creation failed:", error.message);
    return;
  }

  // The unique string UUID generated by Supabase Auth
  const userId = data.user;
  console.log(`User created successfully with ID: ${userId}`);
  return userId;
}
