/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/address": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get user's addresses */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                fullName: string;
                                region: string;
                                city: string;
                                province?: string | null;
                                postalCode: string;
                                barangay: string;
                                addressLine: string;
                                phoneNumber: string;
                                isDefault: boolean;
                                /** Format: uuid */
                                id: string;
                            }[];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fullName: string;
                        region: string;
                        city: string;
                        province?: string | null;
                        postalCode: string;
                        barangay: string;
                        addressLine: string;
                        phoneNumber: string;
                        isDefault: boolean;
                    };
                };
            };
            responses: {
                /** @description Create new address */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                fullName: string;
                                region: string;
                                city: string;
                                province?: string | null;
                                postalCode: string;
                                barangay: string;
                                addressLine: string;
                                phoneNumber: string;
                                isDefault: boolean;
                                /** Format: uuid */
                                id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get user's default address */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                fullName: string;
                                region: string;
                                city: string;
                                province?: string | null;
                                postalCode: string;
                                barangay: string;
                                addressLine: string;
                                phoneNumber: string;
                                isDefault: boolean;
                                /** Format: uuid */
                                id: string;
                            } | null;
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/address/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        fullName?: string;
                        region?: string;
                        city?: string;
                        province?: string | null;
                        postalCode?: string;
                        barangay?: string;
                        addressLine?: string;
                        phoneNumber?: string;
                        isDefault?: boolean;
                    };
                };
            };
            responses: {
                /** @description Update existing address */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                fullName: string;
                                region: string;
                                city: string;
                                province?: string | null;
                                postalCode: string;
                                barangay: string;
                                addressLine: string;
                                phoneNumber: string;
                                isDefault: boolean;
                                /** Format: uuid */
                                id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Address not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
