/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cart/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get user's cart items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                quantity: number;
                                cardMessages: string[];
                                isAvailable: boolean;
                                product: {
                                    /** Format: uuid */
                                    id: string | null;
                                    options: {
                                        name: string;
                                        values: string[];
                                    }[];
                                    name: string;
                                    /** Format: uri */
                                    primaryImageUrl: string;
                                    variant: {
                                        /** Format: uuid */
                                        id: string;
                                        priceCents: number;
                                        attributes: {
                                            [key: string]: string;
                                        };
                                    };
                                };
                            }[];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        quantity: number;
                        /** Format: uuid */
                        productId: string;
                        /** Format: uuid */
                        variantId: string;
                        /** @default [] */
                        cardMessages?: string[] | null;
                    };
                };
            };
            responses: {
                /** @description Add item to cart */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uuid */
                                id: string;
                                quantity: number;
                                cardMessages: string[];
                                isAvailable: boolean;
                                product: {
                                    /** Format: uuid */
                                    id: string | null;
                                    options: {
                                        name: string;
                                        values: string[];
                                    }[];
                                    name: string;
                                    /** Format: uri */
                                    primaryImageUrl: string;
                                    variant: {
                                        /** Format: uuid */
                                        id: string;
                                        priceCents: number;
                                        attributes: {
                                            [key: string]: string;
                                        };
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        cartItemIds: string[];
                    };
                };
            };
            responses: {
                /** @description Delete cart items */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                deletedItemIds: string[];
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cart/items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        newVariantId?: string;
                        quantity?: number;
                        /** @default [] */
                        cardMessages?: string[] | null;
                    };
                };
            };
            responses: {
                /** @description Update cart item */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                item: {
                                    /** Format: uuid */
                                    id: string;
                                    quantity: number;
                                    cardMessages: string[];
                                    isAvailable: boolean;
                                    product: {
                                        /** Format: uuid */
                                        id: string | null;
                                        options: {
                                            name: string;
                                            values: string[];
                                        }[];
                                        name: string;
                                        /** Format: uri */
                                        primaryImageUrl: string;
                                        variant: {
                                            /** Format: uuid */
                                            id: string;
                                            priceCents: number;
                                            attributes: {
                                                [key: string]: string;
                                            };
                                        };
                                    };
                                };
                                /** Format: uuid */
                                deletedItemId: string | null;
                            };
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Cart item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string | {
                                message: string;
                                field?: string;
                            }[];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
