name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "pnpm"

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm type

      - name: Test frontend
        run: pnpm -F frontend test run

      - name: Test backend
        run: pnpm -F backend test

      - name: Build
        run: pnpm build
